---
title: "Info for INFO550"
author: "David Benkeser"
tldr: "Everything you need to know about the course."
recording: ""
reading: ""
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
---

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
style_mono_accent(
  base_color = "#012169",
  header_font_google = google_font("DM Sans"),
  text_font_google   = google_font("DM Sans", "400", "400i"),
  code_font_google   = google_font("Courier Prime")
)
```

<style type="text/css">
.remark-slide-content {
    font-size: 25px
}
</style>

# Basics

* __Course website__: https://benkeser.github.io/info550
* __Meeting__: Thursdays 3:15 - 5:05pm
* __Attendance policy__: In-person attendance possible for first half of semester. In-person attendance is __not required__ but synchronous attendance in Zoom sessions is __strongly encouraged__.

You are encouraged to follow along with code demonstrations on your laptop during class. 

???

Most material for class will be made available via the course website. 
The website is hosted on GitHub and all materials are available at the 
GitHub repository (https://github.com/benkeser/info550). 

Classes will be a mix of lectures and interactive exercises. Synchronous 
attendance is strongly encouraged. 

---

# Learning objectives

* Understand why automation is a key element of reproducible data science.
* Operate capably and comfortably at the command line.
* Implement best practices for version control and open source projects.
* Produce reproducible workflows for data cleaning, analysis and report generation  using the suite of tools learned in the class.
* Create simple R packages.
* Build Docker containers and use them to develop containerized workflows.
* Understand basic uses of bash and python. 
* Utilize Jupyter notebooks.
* Utilize AWS cloud computing services for computation and storage.

---

# What INFO550 is

A class to...
* make your science more reproducible;
* increase the impact of your work by making your code accessible and readable;
* survey tools in modern data science;
* make your life easier. 

???

The goal is to teach best practices that we should strive for in our 
work and to provide motivation and brief introduction to the tools that 
enable us to make that happen. 

---

# What INFO550 is not

A class...
* on machine learning; 
* where the "right" answer is *somewhere* in the slides; 
* that extensively covers any one area in great depth.

???

We will not discuss statistical methodology, though I may at 
times show some basic statistics to illustrate software. 

Learning these tools requires practice and (often a great deal of 
frustration) -- it's part of the process. Thankfully, there is a 
large online community that you can access if you know how. 

---

# The wrong attitude

.center[*Other students may be okay with searching the internet for help with R coding, but that's not very helpful for all students.*]
.center[\- A disgruntled student]

???

Quote from a review of a previous course.

No one writes perfect code. Code breaks. And there's no one in the world
who immediately understands every error message to crop up. You must be 
willing to take the initiative to figure it out. 

Learning to efficiently fix broken code is almost as important as learning
how to write good code in the first place. 

---

# Project

Throughout the semester, you will develop a project. 
* Ideally, something related to your own work. 

Project must: 
* involve data manipulation (download, cleaning);
* data analysis (summary statistics or figures OK);
* report summarizing analysis (including plot and table).

Homework most weeks will be to develop an aspect of the project. 
* A peer will grade you on how easy it is to run your code. 

???

If you do not have access to a real data project at this point, that is 
OK. Try to think about the types of projects you expect to handle and 
develop a project that "looks like" that. What types of tables/figures
are typically produced in your field? Build an automatic script for making
a clean table 1. Build an automatic script for making the results of `glm`
look nice. Fancy statistics are not required. 

An overarching goal of the course is to make you write code that other 
people (or yourself, at a future date) can use. Thus, you will be graded 
precisely on how well your code is documented/how easy it is for another 
person to use it. 

---

# Slides

The slides are created using the [xaringan](https://slides.yihui.org/xaringan/#1) package. 

To print the notes as a .pdf (allegedly works best using Chrome):

* scroll through all slides so content loads;
* File: Print (or `super + p`): Destination: Save as PDF

The slides contain additional "presenter" notes and comments to make the
material more stand alone. 

* enter Presenter Mode by pressing `p`. 



